First pass of mongo schema
harvard-lts/drs-import-management-service pull request #1
Opened 2022-03-04 18:49 UTC by ives1227

**Initial Mongo schema**
* * *

**JIRA Ticket**: [(link)](https://github.com/harvard-lts/HDC/issues/22)

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
MVP Document: https://docs.google.com/document/d/1VYkGjiT7cdLtDi8lzsdpuIXVl8N-eU3BNGzxMNmkPb8/edit#heading=h.o4vjapab0ipm

# What does this Pull Request do?
Adds a first pass at a Mongo Schema for the import management to use.

# How should this be tested?

No testing necessary.

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? No
- integration tests? No

2022-03-07 10:30 UTC, GPortas commented on mongo/schema.json
> +            "",
Is this empty string enum value correct?

2022-03-07 10:52 UTC, GPortas requested changes
Looks good!

Just a small comment related to ingest_status enum.

2022-03-08 14:31 UTC, ives1227 commented on mongo/schema.json
> +            "",
@GPortas that is a good catch - it has no purpose in this workflow.  I've removed it.

2022-03-08 16:17 UTC, ives1227 commented
@GPortas I changed the import status enum.  This should be ready.  Thanks!

2022-03-09 09:22 UTC, GPortas approved these changes
Looks great! 👍  Thank you @ives1227

2022-03-09 13:43 UTC, merged