Python/Flask code base
harvard-lts/drs-import-management-service pull request #2
Opened 2022-03-09 20:39 UTC by GPortas

**JIRA Ticket**: ([link](https://app.zenhub.com/workspaces/hdc-62163f60fb08c60011fa4795/issues/harvard-lts/hdc/13))

# What does this Pull Request do?

Adds the Python/Flask application code base.

The application is executable through Docker and provides a basic /health endpoint.

# How should this be tested?

- Execute the application by creating a container through docker-compose: `docker-compose up` (Docker commands can also be used as an alternative as described in README.md)
- Access http://localhost:5000/health to verify that endpoint returns OK response

# Test coverage
- unit tests? Yes
- integration tests? No

2022-03-09 22:18 UTC, jessjass commented on Dockerfile
> +
We generally have self-signed certs defined in the Dockerfile, but based on our meeting today it seemed like nginx would be handling ssl? I will confirm if we need the self-signed certs in the Dockerfile for this project as well, and we can add them if we do.

2022-03-09 22:18 UTC, jessjass commented on docker-compose.yml
> +      - ENV_CONFIG=development
Env vars are ok here but they can be moved to a .env file. In general, the env vars are added to env.example file (with blanks for passwords) that's pushed to the repo and the dev copies that to a .env file and fill in the necessary passwords. It makes handling secrets and passwords easier in the long run.

2022-03-09 22:28 UTC, jessjass commented on Dockerfile
> +RUN useradd --create-home imsuser
There is another application already called IMS, so to avoid conflict let's use another abbreviation of the service name. This will have to be edited wherever else it's used.

2022-03-09 22:50 UTC, jessjass commented on docker-compose.yml
> +      - "5000:5000"
For deployment, we will want to pick a different host port to and add it to our docker ports documentation. I can confirm what port to use.

2022-03-10 01:33 UTC, ives1227 commented on docker-compose.yml
> +      - "5000:5000"
@jessjass and @GPortas I did assign it port 13880 (Jessi - the wiki).  That is an unused port that can be exposed as the external port.

2022-03-10 01:43 UTC, ives1227 requested changes
This looks great.  Just a small comment about user ids to update on my end.

2022-03-10 01:43 UTC, ives1227 commented on Dockerfile
> +RUN useradd --create-home imsuser
@GPortas and @jessjass how about DIMS (DRS Import Management Service). 

Also, please assign the user and group to ID both to 55020.  This is the user and group ID that the hdc3aadm user on our docker servers uses.  Something like (check the syntax):
```
groupadd -r -g 55020 dimsadm && \
 useradd -u 55020 -g 55020 --create-home imsuser
```

2022-03-10 01:43 UTC, ives1227 commented on app/import_management_service_app.py
> +class ImportManagementServiceApp(FlaskApp):
Glad to see this

2022-03-10 14:41 UTC, jessjass commented on Dockerfile
> +RUN useradd --create-home imsuser
Ya DIMS sounds good to me!

2022-03-10 15:42 UTC, GPortas commented
@jessjass @ives1227 Thank you for your comments. Great improvements!

I just updated the code with the requested changes. Do not hesitate to tell me anything else you see that could be improved.

2022-03-10 16:52 UTC, jessjass commented on Dockerfile
> +
Based on what @captmiddy mentioned in a slack convo, the self-signed certs will be added to the nginx container.

2022-03-10 16:54 UTC, jessjass commented on docker-compose.yml
> +      - ./app:/home/imsuser/app
This should also be dimsuser

2022-03-11 14:40 UTC, ives1227 approved these changes

2022-03-11 14:41 UTC, merged