Add basic publishing messaging capabilities
harvard-lts/drs-import-management-service pull request #6
Opened 2022-03-16 18:09 UTC by GPortas

**Add basic publishing messaging capabilities**
* * *

**GitHub Issue**: [(link)](https://app.zenhub.com/workspaces/hdc-62163f60fb08c60011fa4795/issues/harvard-lts/hdc/18)

# What does this Pull Request do?
This PR includes the following relevant changes:

- Basic message publisher, which publishes an empty dummy message to a MQ.
- OpenAPI spec file for API endpoint documentation and OpenAPI-Controllers mapping using connexion.
- Local integration test environment.
- More advanced code layering, separating domain and application layers at the moment (Exception handling and propagation is also layer-oriented).
- Dependency Injection setup.

_/ingest endpoint currently does not receive a request body and returns a basic response for a first pass. Both the name of the endpoint and the request and response bodies are open to modification when the DIMS endpoints are finally defined._

# How should this be tested?

A description of what steps someone could take to:
* Create/Update .env and .test.env files as described in README.md
* Run the local development environment: `docker-compose -f docker-compose-dev.yml up`
* Access local development ActiveMQ frontend http://localhost:8161/admin/ (User: admin, Password: admin)
* Go to queues section: http://localhost:8161/admin/queues.jsp
* POST to http://localhost:10580/ingest
* In the queues section, there should appear a message posted to dev_queue
* Run the local test environment: `docker-compose -f docker-compose-test.yml up`
* Execute integration test TestInitiateIngestQueuePublisher: `docker exec -it test_runner pytest test/integration`

# Test coverage
- unit tests Yes
- integration tests Yes

# Interested parties
@jessjass @ives1227

2022-03-17 02:54 UTC, ives1227 requested changes
Hi @GPortas, this is all coming along.
1.  I followed your steps to run the dev setup.  Everything spun up but when I tried to POST to http://localhost:13880/ingest, I received the following errors:
```
Could not connect to host dev_activemq, port 61613
192.168.160.1 - - [17/Mar/2022 02:48:57] "POST /ingest HTTP/1.1" 500 -
```
2. I moved on to running the integration test but realized that I needed a lot of things installed on my computer. I left you a comment and sample about pushing it into a Dockerfile.
3. Please make sure to put inline and block comments into your code so someone reading through can understand the purpose of each class and method.

Thanks for all of your great work!

2022-03-17 02:54 UTC, ives1227 commented on README.md
> +
You have a great test setup.  Two things - it would be best if the testing environment could be pushed into a docker container that has the correct versions of Python.  Otherwise, the developer that is testing has to have the correct installations on their computer.  A simple container that has the necessary installations that a user can exec into is fine.  For example, this Dockerfile has very little in it but has a 3.8 version of python (you would have to modify the base image to get your required 3.10): https://github.com/harvard-lts/drs-translation-service/blob/main/DockerfileLocal. Please let me know I can help in any way. 

Second, it would be helpful if you could put exact commands for running an individual test or group of tests.

2022-03-17 16:10 UTC, GPortas commented on README.md
> +
Your suggestions are great.

Following your approach, I have created a test runner container within the same test environment to execute tests and I have also edited the README.md to explain how to execute the different types of tests (unit and integration) separately or together using the test runner container.

I would also like to use exact commands as you suggest. If it's okay to you, in order to not extend more this PR, we can look at that improvement for a future iteration.

Thank you!

2022-03-18 13:56 UTC, ives1227 commented on README.md
> +
@jessjass was able to test it without incident so I'm going to approve and merge.

2022-03-18 13:57 UTC, ives1227 approved these changes

2022-03-18 16:10 UTC, merged